services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ibm-hackathon-client
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    command: npm run dev:host
